### ISSUE TITLE
Navigation menu connected to permissions

### ISSUE THREAD

**Issue by alxlapin** [cusodede/ppl#21]
Реализовать вывод элементов навигационного меню в соответствии с выданными разрешениями

**Comment by pozitronik** [comment]
Нужно в модуле разрешений добавить метод, проверяющий наличие у пользователя доступа к Controller/action.
Сейчас есть UsersPermissionsTrait::hasActionPermission, нужно на его основе забубенить.
На мне https://github.com/cusodede/bc/issues/16

**Comment by pozitronik** [comment]
Готово, реализацию смотри в
https://github.com/cusodede/bc/blob/680732e7ba852e58261363f522dfb7157ae85be9/views/layouts/subviews/sidebar.php#L35
и дальше оттуда
