### ISSUE TITLE
getIsTechUser() - флаг технического пользователя?

### ISSUE THREAD

**Issue by pozitronik** [cusodede/ppl#68]
Я не думаю, что делать эту проверку хардкодом было бы правильно, это же чисто конфигурационная вещь. Если объяснишь, что подразумевается под технической записью, возможно найдём способ сделать это через конфигурацию прав доступа.

_Originally posted by @pozitronik in https://github.com/cusodede/ppl/pull/67#discussion_r668574734_

**Comment by alxlapin** [comment]
Под техническими подразумеваются системные пользователи, которых мы будем заводить для идентификации партнерских приложений/сервисов. Эти сервисы будут взаимодействовать с нами посредством АПИ. Предполагалось, что мы добавим в таблицу sys_users категорию (или тип, doesn't matter). И вот техническая запись - это как раз одна из категорий.

**Comment by pozitronik** [comment]
> 
> 
> Эти сервисы будут взаимодействовать с нами посредством АПИ. Предполагалось, что мы добавим в таблицу sys_users категорию (или тип, doesn't matter). И вот техническая запись - это как раз одна из категорий.

Может быть, тогда стоит их просто правами выставлять? Создать пермишен `api_service` и в нужных местах проверять через
```php
$user->hasPermission(['api_service'])
```

?

**Comment by alxlapin** [comment]
Можно и так разруливать нужные проверки. Но логическая связность теряется, разве нет? То есть попытка выделить принадлежность пользователя к определенной группе через пермиссии.
